# Generated by Django 6.0.2 on 2026-03-01 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise_type', models.CharField(choices=[('squat', 'Squat'), ('bench', 'Bench Press'), ('deadlift', 'Deadlift'), ('custom', 'Custom')], max_length=20)),
                ('exercise_name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Training Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
